# OpenFace: cleaning up the mess
# 2 8 2021
# Julianna Calabrese

# the goal of this file is to take
# all the big openface csv files
# that have not-needed info on head position and eye gaze
# and get rid of that not-needed info
# and then just write out all the smaller csv files
# so we can just focus on the variables that we want

# the processed folder has everything generated by openface
# which includes csv, png, and video files
# the csv folder just contains openface csv files
# the small folder (which this rscript populates)
# contains these smaller csv files 
# after i ran this, i uploaded the entire small folder 
# to my onedrive
# so i could access it better later
# because this linux server is so slow
# this rscript can only be run on the linux server

# set directory
setwd("/data/csv")

# do a thing from stackoverflow
# this puts all the csv files in the csv folder
# in a big list
filelist <- list.files(pattern="*.csv", full.names=TRUE)
lst <- lapply(filelist, read.csv, header=TRUE, stringsAsFactors=FALSE)
# the line below this selects only the columns we're interested in
lst1 <- lapply(lst, "[", c(1:5,680:714))
rm(lst)

# fix names
names(lst1) <- filelist
names(lst1) <- substring(names(lst1), 3)

# set a new directory
setwd("/data/small")

# do another thing from stackoverflow
# this writes out all the smaller csv files
# individually into the small folder
lapply(1:length(lst1), function(i) write.csv(lst1[[i]], 
                                             file = paste0(names(lst1[i])),
                                             row.names = FALSE))

# and then when you're done, just manually
# upload the folder to a server
# that more easily accessible


